### ISSUE TITLE
Overflows

### ISSUE THREAD

**Issue by weissi** [tomerd/swift-server-metrics-api-proposal#16]
We should think about integer overflows, kinda likely to happen with metrics and you wouldn’t want to crash for metrics.

We could check for them explicitly or use `&+` and friends instead of `+` but that’s only defined behaviour for unsigned ints I think (that’s how it is in C , overflow defined for unsigned and undefined for signed ints).

This is just to remind us to think about it and write tests.

**Comment by weissi** [comment]
Nio has examples for overflow tests: https://github.com/apple/swift-nio/blob/06649bb8c704a042fc07f2013ae429e2d646e7bb/Tests/NIOTests/ByteBufferTest.swift#L938

**Comment by MrLotU** [comment]
Is it feasible to switch from integers to Doubles? (Also see #15) since they don't crash on overflow? I'm not sure what the differences between an `Int64` and a `Double` would be performance wise, but I don't think we'd lose anything feature wise.

**Comment by weissi** [comment]
> Is it feasible to switch from integers to Doubles? (Also see #15)

Only if you can live with losing more and more precision the bigger the numbers get (arguably they have to be quite big)

```
20> (1.0000000000000005E+125 + 100) - 1.0000000000000005E+125 
$R18: Double = 0
```


> since they don't crash on overflow? I'm not sure what the differences between an `Int64` and a `Double` would be performance wise, but I don't think we'd lose anything feature wise.

I mean they go to `+/-Inf` if the numbers go massively big:

```
  1> let x: Double = 9999999999999999999999999
x: Double = 1.0000000000000001E+25
  2> x*x
$R0: Double = 1.0000000000000003E+50
  3> x*x*x
$R1: Double = 1.0000000000000003E+75
  4> x*x*x*x
$R2: Double = 1.0000000000000004E+100
  5> x*x*x*x*x
$R3: Double = 1.0000000000000005E+125
  6> x*x*x*x*x*x
$R4: Double = 1.0000000000000005E+150
  7> x*x*x*x*x*x*x
$R5: Double = 1.0000000000000006E+175
  8> x*x*x*x*x*x*x*x
$R6: Double = 1.0000000000000006E+200
  9> (x*x*x*x*x*x*x*x) * (x*x*x*x*x*x*x*x)
$R7: Double = +Inf
```

but that's probably not relevant.

**Comment by tomerd** [comment]
@weissi is your concern with operations done at the API library (ie this one) that may overflow, or backend implementations that perform aggregations, etc? the latter are more likely, tho i agree we should add some verification to make sure the API does not fall into that trap

**Comment by milseman** [comment]
My understanding is that you want to be able to increment by 1. If so, a corresponding fixed-width integer gives you a domain thousands of times larger than you can represent than Doubles.

**Comment by tomerd** [comment]
@milseman i assume you are answering @MrLotU?

**Comment by weissi** [comment]
> My understanding is that you want to be able to increment by 1. If so, a corresponding fixed-width integer gives you a domain thousands of times larger than you can represent than Doubles.

I also think fixed-with is the right thing to do for counters etc but we should test for potential overflows and decide how to handle.



> @weissi is your concern with operations done at the API library (ie this one) that may overflow, or backend implementations that perform aggregations, etc? the latter are more likely, tho i agree we should add some verification to make sure the API does not fall into that trap

I don't actually know :). I mostly wanted to file this so that we think about it (and test for it). I don't have a real opinion yet what should happen if say a counter overflows (except that it shouldn't be a crash :) )

The other thing we should do after deciding what's the right answer is to document how the backend should behave.

**Comment by tomerd** [comment]
now tracked in https://github.com/apple/swift-metrics/issues/5
