### ISSUE TITLE
Metrics Timer usability improvement idea

### ISSUE THREAD

**Issue by Blejwi** [tomerd/swift-server-metrics-api-proposal#2]
Hello,

Great work with standardizing metrics API, can't wait to use it in my projects!

The current implementation is very flexible but also requires some manual work:
```
Metrics.global.withTimer(label: "RandomLibrary::doSomethingSlow") { timer in
    let start = Date()
    DispatchQueue.global().asyncAfter(deadline: .now() + .milliseconds(Int.random(in: 5 ... 500))) {
        timer.record(Date().timeIntervalSince(start))
        callback()
    }
}
```
### withTimer Function simplification
Getting intervals manually is great for custom scenarios but might be simplified for some standard usages:
If a function is synchronous, it would be great to use it in a simpler way:
```
func doSomethingSlowSynchronously(callback: @escaping () -> Void) {
    Metrics.global.withTimer(label: "RandomLibrary::doSomethingSlowSynchronously") {
        sleep(1)
        callback()
    }
}
```
```
public extension MetricsHandler {
    @inlinable
    func withTimer(label: String, dimensions: [(String, String)] = [], then: () -> Void) {
        let start = Date()
        let timer = self.makeTimer(label: label, dimensions: dimensions)
        then()
        timer.recordSeconds(Date().timeIntervalSince(start))
    }
}
```
No need to manually work with Date and Intervals.

### Timer usage simplification
The other usage simplification that may be done is adding some sort of start/stop methods to Timer instance. Timer instance could run `start` method (it might be even run when initializing `Timer`) and `stop` method on `record` call (if no value is provided). 

```
public extension Timer {
	private let startTime: Date
	
    public init() {
        self.start()
    }

    private func start() {
        return self.startTime = Date()
    }
	
    private func stop() -> TimeInterval {
        return Date().timeIntervalSince(self.startTime)
    }

    func record(_ duration: TimeInterval) {
        self.recordSeconds(duration)
    }

    func record() {
        let duration = self.stop()
        self.record(duration)
    }
}
```

Such changes would simplify the example from the previous section:
```
public extension MetricsHandler {
    @inlinable
    func withTimer(label: String, dimensions: [(String, String)] = [], then: () -> Void) {
        let timer = self.makeTimer(label: label, dimensions: dimensions)
        then()
        timer.record()
    }
}
```
Manual usage of `Timer` (not via `withTimer` method) would be much easier as well without calculating `TimeInterval` manually.

Please let me know what do you think about such changes.

_Please note that code here is just proposal and will not work when copy-pasted :)_

**Comment by tomerd** [comment]
@Blejwi good ideas, there is something similar [here](https://github.com/tomerd/swift-server-metrics-api-proposal/blob/master/Sources/Metrics/Metrics.swift#L7), does it cover the need?

**Comment by tomerd** [comment]
wrt to the following

```
public init() {
  self.start()
}

private func start() {
  return self.startTime = Date()
}
```

i think its a problem to assume you start measuring on creation of the timer. wdyt?

**Comment by Blejwi** [comment]
@tomerd Yup, sorry, didn't see it before.

I think you are right, measuring on creating might be confusing for users.
But I still think it's worth adding start/stop methods to simplify usage (no need to manually work with Date and Interval). What do you think?

**Comment by tomerd** [comment]
@Blejwi thanks for your feedback and help, lets move this / future discussions to the now official repo: https://github.com/apple/swift-metrics
